spring:
  application:
      name: Bank-Account-Management-System
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_data_base
    username: postgres
    password: NoP4$$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: asim
      password: asim


