spring:
  application:
      name: Bank-Account-Management-System
  datasource:
    url: jdbc:postgresql://localhost:5436/bank_data_base
    username: postgres
    password: password
#    password: NoP4$$
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: asim
      password: asim
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MY_EMAIL_APP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




