spring:
  application:
      name: Bank-Account-Management-System
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: asim
      password: asim
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MY_EMAIL}
    password: ${MY_EMAIL_APP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


frontend:
  url: ${FRONTEND_URL}

